#!/bin/bash
C_B_BLUE='\E[1;44m'					# set : color blue (background)
C_B_GREEN='\E[1;42m'					# set : color green (background)
C_B_RED='\E[1;41m'					# set : color red (background)
C_D_NULL="/dev/null"					# set : character device /dev/null
C_D_ZERO="/dev/zero"					# set : character device /dev/zero
C_F_BLUE='\E[1;34m'					# set : color blue (font)
C_F_GREEN='\E[1;32m'					# set : color green (font)
C_F_LINE='\E[4m'					# set : line  underline (font)
C_F_PINK='\E[1;35m'					# set : color pink (font)
C_F_RED='\E[1;31m'					# set : color red (font)
C_F_RES='\E[0m'						# set : color null end
C_F_YELOW='\E[1;33m'					# set : color yelow (font)
D_FORMAT=$(date +%Y-%m-%d-%H-%M-%S)			# set : date format
F_N_APU_E100=uos_gg3x_e100.srec				# set : file name apu e100
F_N_APU_SRECA_E100=uos_gg3x_e100_a.srec			# set : file name apu e100 a.srec
F_N_APU_SRECB_E100=uos_gg3x_e100_b.srec			# set : file name apu e100 b.srec
F_N_APU_E100W=uos_gg3x_e100w_v2.srec			# set : file name apu e100w
F_N_APU_SRECA_E100W=uos_gg3x_e100w_v2_a.srec		# set : file name apu e100w a.srec
F_N_APU_SRECB_E100W=uos_gg3x_e100w_v2_b.srec		# set : file name apu e100w b.srec
F_P_HOME=/home/worker					# set : file path home /home/worker
F_P_APU=${F_P_HOME}/firmware/APU			# set : file path apu /home/worker/firmware/APU
F_P_APU_HOST=${F_P_APU}/host				# set : file path apu /home/worker/firmware/APU/host
F_P_APU_TARGET=${F_P_APU}/target			# set : file path apu /home/worker/firmware/APU/target
F_P_RELEASE=/etc/uisee_release				# set : file path uisee_release /etc
F_P_SYSTEM=/etc/systemd/system				# set : file path system service /etc/systemd/system
R_P_HOME=/home/worker					# set : run path home /home/worker
R_P_MAIN=${R_P_HOME}/GG31_SYSTEM			# set : run path main /home/worker/GG31_SYSTEM
R_P_BIN=${R_P_MAIN}/bin					# set : run path etc /home/worker/GG31_SYSTEM/bin
R_P_BIN_MODULE=${R_P_BIN}/monitor_module		# set : run path etc /home/worker/GG31_SYSTEM/bin/monitor_module
R_P_ETC=${R_P_MAIN}/etc					# set : run path etc /home/worker/GG31_SYSTEM/etc
R_P_LIB=${R_P_MAIN}/lib					# set : run path lib /home/worker/GG31_SYSTEM/lib
R_P_LIB_DEB=${R_P_LIB}/deb_package			# set : run path lib /home/worker/GG31_SYSTEM/lib/deb_package
R_P_LIB_FILE=${R_P_LIB}/file_attached			# set : run path lib /home/worker/GG31_SYSTEM/lib/file_attached
R_P_LIB_HTML=${R_P_LIB}/html_attached			# set : run path lib /home/worker/GG31_SYSTEM/lib/html_attached
R_P_LOG=${R_P_MAIN}/log					# set : run path log /home/worker/GG31_SYSTEM/log
R_P_LOG_APU=${R_P_LOG}/check_apu/			# set : run path log /home/worker/GG31_SYSTEM/log/check_apu
R_P_LOG_APU_A=${R_P_LOG}/check_apu/abnormal/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_apu/abnormal/xxxx-xx-xx-xx-xx-xx
R_P_LOG_APU_N=${R_P_LOG}/check_apu/normal/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_apu/normal/xxxx-xx-xx-xx-xx-xx
R_P_LOG_CDU=${R_P_LOG}/check_cdu/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_cdu/xxxx-xx-xx-xx-xx-xx
R_P_LOG_CPU=${R_P_LOG}/check_cpu/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_cpu/xxxx-xx-xx-xx-xx-xx
R_P_LOG_DGPS=${R_P_LOG}/check_dgps/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_dgps/xxxx-xx-xx-xx-xx-xx
R_P_LOG_DSI=${R_P_LOG}/check_dsi/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_dsi/xxxx-xx-xx-xx-xx-xx
R_P_LOG_GPU=${R_P_LOG}/check_gpu/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_gpu/xxxx-xx-xx-xx-xx-xx
R_P_LOG_IPERF=${R_P_LOG}/check_iperf/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_iperf/xxxx-xx-xx-xx-xx-xx
R_P_LOG_MONITOR=${R_P_LOG}/check_monitor/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_monitor/xxxx-xx-xx-xx-xx-xx
R_P_LOG_NETWORK=${R_P_LOG}/check_network/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_network/xxxx-xx-xx-xx-xx-xx
R_P_LOG_SSD=${R_P_LOG}/check_ssd/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_ssd/xxxx-xx-xx-xx-xx-xx
R_P_LOG_STATISTIC=${R_P_LOG}/check_statistic/${D_FORMAT}	# set : run path log /home/worker/GG31_SYSTEM/log/check_statistic/xxxx-xx-xx-xx-xx-xx
R_P_LOG_TEMP=${R_P_LOG}/check_temp/${D_FORMAT}		# set : run path log /home/worker/GG31_SYSTEM/log/check_temp/xxxx-xx-xx-xx-xx-xx
R_P_OPT=${R_P_MAIN}/opt					# set : run path opt /home/worker/GG31_SYSTEM/opt
S_L_STR0=$(printf "%-80s" "-")				# set : separation line "-"
S_L_STR1=$(printf "%-80s" "=")				# set : separation line "="
S_L_STR2=$(printf "%-80s" "*")				# set : separation line "*"
P_I_MASTER="192.168.100.99"				# set : port ip master 
P_I_SLAVE="192.168.100.98"				# set : port ip slave
P_I_BLACK="192.168.100.77"				# set : port ip blackbox
P_I_LIDAR="192.168.100.201"				# set : port ip lidar
